import Foundation

struct Word: Identifiable, Hashable {
    let rank: Int
    let word: String
    let pos: String
    let ipa: String
    let def: String
    let alt: String?
    let ex1: String
    let ex2: String?
    let id_translation: String
    let idDef: String?
    let idEx1: String?

    var id: Int { rank }
}

// MARK: – Static dataset (60 sample words from frequency list)
extension Word {
    static let all: [Word] = [
        Word(rank: 1,   word: "the",          pos: "article",     ipa: "/ðə/",          def: "Used to point forward to a noun already known or about to be specified.",          alt: "Denoting one or more people or things already mentioned.",             ex1: "Pass me the book on the table.",             ex2: "The sun rose over the hills.",         id_translation: "itu / yang",                          idDef: "Digunakan untuk menunjuk kata benda yang sudah diketahui.",             idEx1: "Berikan buku itu padaku."),
        Word(rank: 2,   word: "be",           pos: "verb",        ipa: "/biː/",         def: "To exist or be present; to occupy a place or position.",                          alt: "To have a specified quality or condition.",                            ex1: "I think, therefore I am.",                   ex2: "There will be time later.",            id_translation: "ada / adalah / berada",               idDef: "Untuk ada atau hadir; menempati suatu tempat.",                        idEx1: "Aku berpikir, maka aku ada."),
        Word(rank: 3,   word: "to",           pos: "preposition", ipa: "/tuː/",         def: "Expressing motion in the direction of a particular location.",                     alt: "Identifying the recipient of something.",                              ex1: "We walked to the river.",                    ex2: "Give the keys to her.",                id_translation: "ke / untuk / kepada",                 idDef: "Menyatakan gerakan menuju suatu lokasi.",                              idEx1: "Kami berjalan ke sungai."),
        Word(rank: 4,   word: "of",           pos: "preposition", ipa: "/ɒv/",          def: "Expressing the relationship between a part and a whole.",                          alt: "Belonging to or associated with.",                                     ex1: "A slice of bread.",                          ex2: "The colour of the sky.",               id_translation: "dari / milik",                        idDef: "Menyatakan hubungan antara bagian dan keseluruhan.",                   idEx1: "Sepotong roti."),
        Word(rank: 5,   word: "and",          pos: "conjunction", ipa: "/ænd/",         def: "Used to connect words or clauses of the same kind.",                               alt: "Used to introduce a consequence.",                                     ex1: "Bread and butter.",                          ex2: "Wait and see what happens.",           id_translation: "dan",                                 idDef: "Digunakan untuk menghubungkan kata atau klausa yang sejenis.",         idEx1: "Roti dan mentega."),
        Word(rank: 11,  word: "have",         pos: "verb",        ipa: "/hæv/",         def: "To possess, own, or hold something.",                                              alt: "To experience or undergo.",                                            ex1: "They have a small house.",                   ex2: "We had a wonderful time.",             id_translation: "memiliki / mempunyai",                idDef: "Untuk memiliki atau memegang sesuatu.",                               idEx1: "Mereka memiliki rumah kecil."),
        Word(rank: 23,  word: "with",         pos: "preposition", ipa: "/wɪð/",         def: "Accompanied by another person or thing.",                                          alt: "Using a particular instrument or means.",                              ex1: "She came with her friends.",                 ex2: "Cut it with a knife.",                 id_translation: "dengan / bersama",                    idDef: "Ditemani oleh orang atau hal lain.",                                  idEx1: "Dia datang bersama teman-temannya."),
        Word(rank: 42,  word: "about",        pos: "preposition", ipa: "/əˈbaʊt/",      def: "On the subject of; concerning.",                                                   alt: "Approximately; near to.",                                              ex1: "A film about the ocean.",                    ex2: "It costs about ten pounds.",           id_translation: "tentang / sekitar",                   idDef: "Mengenai suatu topik atau hal tertentu.",                             idEx1: "Sebuah film tentang lautan."),
        Word(rank: 58,  word: "think",        pos: "verb",        ipa: "/θɪŋk/",        def: "To have a particular opinion, belief, or idea about something.",                   alt: "To direct one's mind toward someone or something.",                    ex1: "I think it will rain today.",                ex2: "She thought about her answer.",        id_translation: "berpikir / menganggap",               idDef: "Memiliki pendapat atau gagasan tentang sesuatu.",                     idEx1: "Saya pikir hari ini akan hujan."),
        Word(rank: 67,  word: "because",      pos: "conjunction", ipa: "/bɪˈkɒz/",      def: "For the reason that; since.",                                                      alt: "Used to introduce a cause.",                                           ex1: "We stayed in because it rained.",            ex2: "He left because he was tired.",        id_translation: "karena / sebab",                      idDef: "Untuk alasan bahwa; oleh karena itu.",                                idEx1: "Kami tinggal di dalam karena hujan."),
        Word(rank: 88,  word: "world",        pos: "noun",        ipa: "/wɜːld/",       def: "The earth, together with all of its countries and peoples.",                       alt: "A particular region or group viewed as a unit.",                       ex1: "News from around the world.",                ex2: "The world of fashion.",                id_translation: "dunia / bumi",                        idDef: "Bumi beserta semua negara dan masyarakatnya.",                        idEx1: "Berita dari seluruh dunia."),
        Word(rank: 104, word: "between",      pos: "preposition", ipa: "/bɪˈtwiːn/",    def: "In the space separating two points, objects, or people.",                          alt: "Shared by two or more parties.",                                       ex1: "The town lies between two rivers.",          ex2: "Split the bill between us.",           id_translation: "di antara / antara",                  idDef: "Dalam ruang yang memisahkan dua titik.",                              idEx1: "Kota itu terletak di antara dua sungai."),
        Word(rank: 119, word: "important",    pos: "adjective",   ipa: "/ɪmˈpɔːtənt/",  def: "Of great significance or value; likely to have a serious effect.",                 alt: "Having high rank or status.",                                          ex1: "An important decision.",                     ex2: "It is important to rest.",             id_translation: "penting / berpengaruh",               idDef: "Memiliki arti atau nilai yang besar.",                                idEx1: "Sebuah keputusan penting."),
        Word(rank: 137, word: "develop",      pos: "verb",        ipa: "/dɪˈveləp/",    def: "To grow or cause to grow and become more advanced.",                               alt: "To create or produce over time.",                                      ex1: "Children develop quickly.",                  ex2: "They developed a new method.",         id_translation: "berkembang / mengembangkan",          idDef: "Tumbuh atau menjadi lebih maju.",                                     idEx1: "Anak-anak berkembang dengan cepat."),
        Word(rank: 152, word: "language",     pos: "noun",        ipa: "/ˈlæŋɡwɪdʒ/",  def: "The method of human communication using words in a structured way.",               alt: "The system of a particular community or country.",                     ex1: "She speaks three languages.",                ex2: "The beauty of the language.",          id_translation: "bahasa",                              idDef: "Metode komunikasi manusia menggunakan kata-kata.",                    idEx1: "Dia berbicara tiga bahasa."),
        Word(rank: 168, word: "remember",     pos: "verb",        ipa: "/rɪˈmembə/",    def: "To have or keep an image or idea in your mind of something from the past.",        alt: "To bear in mind; not forget to do.",                                   ex1: "I remember that summer well.",               ex2: "Remember to lock the door.",           id_translation: "mengingat / ingat",                   idDef: "Memiliki gambaran dalam pikiran tentang masa lalu.",                  idEx1: "Saya ingat musim panas itu dengan baik."),
        Word(rank: 183, word: "moment",       pos: "noun",        ipa: "/ˈməʊmənt/",    def: "A very brief period of time.",                                                     alt: "An exact point in time.",                                              ex1: "Wait just a moment.",                        ex2: "At that moment, the lights went out.", id_translation: "saat / momen / sebentar",             idDef: "Periode waktu yang sangat singkat.",                                  idEx1: "Tunggu sebentar."),
        Word(rank: 201, word: "achieve",      pos: "verb",        ipa: "/əˈtʃiːv/",     def: "To successfully bring about or reach a desired objective by effort.",              alt: "To attain a standard or level.",                                       ex1: "She achieved her goal.",                     ex2: "We achieved record sales.",            id_translation: "mencapai / meraih",                   idDef: "Berhasil mewujudkan tujuan melalui usaha.",                           idEx1: "Dia meraih tujuannya."),
        Word(rank: 224, word: "describe",     pos: "verb",        ipa: "/dɪˈskraɪb/",   def: "To give a detailed account in words of someone or something.",                     alt: "To mark out or draw a shape.",                                         ex1: "Describe what you saw.",                     ex2: "He described the scene vividly.",      id_translation: "menggambarkan / mendeskripsikan",     idDef: "Memberikan keterangan rinci tentang seseorang atau sesuatu.",         idEx1: "Gambarkan apa yang kamu lihat."),
        Word(rank: 246, word: "consider",     pos: "verb",        ipa: "/kənˈsɪdə/",    def: "To think carefully about something before making a decision.",                     alt: "To regard in a specified way.",                                        ex1: "Consider the consequences.",                 ex2: "We consider her a friend.",            id_translation: "mempertimbangkan / menganggap",       idDef: "Memikirkan sesuatu dengan hati-hati.",                                idEx1: "Pertimbangkan konsekuensinya."),
        Word(rank: 268, word: "available",    pos: "adjective",   ipa: "/əˈveɪləbəl/",  def: "Able to be used or obtained; at someone's disposal.",                              alt: "Free to see or talk to people.",                                       ex1: "Tickets are still available.",               ex2: "The doctor is available now.",         id_translation: "tersedia / ada",                      idDef: "Dapat digunakan atau diperoleh; siap dipakai.",                       idEx1: "Tiket masih tersedia."),
        Word(rank: 291, word: "community",    pos: "noun",        ipa: "/kəˈmjuːnəti/", def: "A group of people living in the same place or sharing a characteristic.",          alt: "A feeling of fellowship with others.",                                 ex1: "A close-knit community.",                    ex2: "The scientific community.",            id_translation: "komunitas / masyarakat",              idDef: "Sekelompok orang yang berbagi karakteristik.",                        idEx1: "Komunitas yang erat."),
        Word(rank: 312, word: "particular",   pos: "adjective",   ipa: "/pəˈtɪkjələ/",  def: "Used to single out an individual member of a group or class.",                    alt: "Insisting on a high standard; fussy.",                                 ex1: "This particular case is rare.",              ex2: "She is particular about tidiness.", id_translation: "tertentu / khusus",                   idDef: "Digunakan untuk memilih anggota dari kelompok.",                      idEx1: "Kasus tertentu ini jarang terjadi."),
        Word(rank: 339, word: "experience",   pos: "noun",        ipa: "/ɪkˈspɪəriəns/",def: "Practical contact with and observation of facts or events.",                       alt: "An event or occurrence that affects one.",                             ex1: "Years of teaching experience.",              ex2: "A memorable experience.",              id_translation: "pengalaman",                          idDef: "Kontak praktis dengan fakta atau peristiwa.",                         idEx1: "Bertahun-tahun pengalaman mengajar."),
        Word(rank: 367, word: "knowledge",    pos: "noun",        ipa: "/ˈnɒlɪdʒ/",     def: "Facts, information, and skills acquired through experience or education.",         alt: "Awareness or familiarity gained.",                                     ex1: "A thirst for knowledge.",                    ex2: "To the best of my knowledge.",         id_translation: "pengetahuan / ilmu",                  idDef: "Fakta dan keterampilan yang diperoleh melalui pendidikan.",            idEx1: "Haus akan pengetahuan."),
        Word(rank: 388, word: "necessary",    pos: "adjective",   ipa: "/ˈnesəsəri/",    def: "Required to be done, achieved, or present; needed.",                               alt: "Inevitable; determined by circumstances.",                             ex1: "Take the necessary steps.",                  ex2: "It is not necessary to wait.",         id_translation: "perlu / diperlukan",                  idDef: "Harus dilakukan atau ada; dibutuhkan.",                               idEx1: "Ambil langkah-langkah yang diperlukan."),
        Word(rank: 410, word: "opportunity",  pos: "noun",        ipa: "/ˌɒpəˈtjuːnəti/",def: "A set of circumstances that makes it possible to do something.",                  alt: "A chance for advancement.",                                            ex1: "A golden opportunity.",                      ex2: "Seize the opportunity.",               id_translation: "kesempatan / peluang",                idDef: "Keadaan yang memungkinkan sesuatu untuk dilakukan.",                  idEx1: "Kesempatan emas."),
        Word(rank: 433, word: "environment",  pos: "noun",        ipa: "/ɪnˈvaɪrənmənt/",def: "The surroundings or conditions in which a person or thing lives.",                alt: "The natural world as a whole.",                                        ex1: "A relaxed working environment.",             ex2: "Protecting the environment.",          id_translation: "lingkungan",                          idDef: "Lingkungan sekitar di mana seseorang tinggal.",                       idEx1: "Lingkungan kerja yang santai."),
        Word(rank: 455, word: "particularly", pos: "adverb",      ipa: "/pəˈtɪkjələli/", def: "To a higher degree than is usual or average; especially.",                         alt: "In a way that relates to one case.",                                   ex1: "It was particularly cold.",                  ex2: "I particularly liked the ending.",     id_translation: "terutama / khususnya",                idDef: "Pada tingkat yang lebih tinggi dari biasanya.",                       idEx1: "Cuacanya sangat dingin."),
        Word(rank: 478, word: "represent",    pos: "verb",        ipa: "/ˌreprɪˈzent/",  def: "To act or speak officially on behalf of another person or group.",                 alt: "To be a specimen or example of.",                                      ex1: "She represents the region.",                 ex2: "The colours represent peace.",         id_translation: "mewakili / merepresentasikan",        idDef: "Bertindak atas nama orang atau kelompok lain.",                       idEx1: "Dia mewakili daerah tersebut."),
        Word(rank: 502, word: "significant",  pos: "adjective",   ipa: "/sɪɡˈnɪfɪkənt/", def: "Sufficiently great or important to be worthy of attention.",                      alt: "Having a particular meaning.",                                         ex1: "A significant improvement.",                 ex2: "A significant glance.",                id_translation: "signifikan / bermakna",               idDef: "Cukup besar sehingga layak diperhatikan.",                            idEx1: "Peningkatan yang signifikan."),
        Word(rank: 531, word: "determine",    pos: "verb",        ipa: "/dɪˈtɜːmɪn/",   def: "To cause something to occur in a particular way; to establish exactly.",           alt: "To firmly decide on a course.",                                        ex1: "Genes determine eye colour.",                ex2: "We must determine the cause.",         id_translation: "menentukan / menetapkan",             idDef: "Menetapkan sesuatu dengan tepat.",                                    idEx1: "Gen menentukan warna mata."),
        Word(rank: 559, word: "approach",     pos: "noun",        ipa: "/əˈprəʊtʃ/",    def: "A way of dealing with something; a method.",                                       alt: "The act of coming near in space or time.",                             ex1: "A fresh approach to the problem.",           ex2: "The approach of winter.",              id_translation: "pendekatan / cara",                   idDef: "Cara menangani sesuatu; suatu metode.",                               idEx1: "Pendekatan baru terhadap masalah."),
        Word(rank: 588, word: "individual",   pos: "noun",        ipa: "/ˌɪndɪˈvɪdʒuəl/",def: "A single human being as distinct from a group.",                                  alt: "Single; separate.",                                                    ex1: "Each individual is unique.",                 ex2: "Individual portions of cake.",         id_translation: "individu / perorangan",               idDef: "Satu manusia yang berbeda dari kelompok.",                            idEx1: "Setiap individu itu unik."),
        Word(rank: 644, word: "establish",    pos: "verb",        ipa: "/ɪˈstæblɪʃ/",   def: "To set up on a firm or permanent basis.",                                          alt: "To show something to be true.",                                        ex1: "They established a company.",                ex2: "We must establish the facts.",         id_translation: "mendirikan / menetapkan",             idDef: "Mendirikan dengan dasar yang kuat.",                                  idEx1: "Mereka mendirikan sebuah perusahaan."),
        Word(rank: 673, word: "perhaps",      pos: "adverb",      ipa: "/pəˈhæps/",      def: "Used to express uncertainty or possibility.",                                      alt: "Used to make a polite request.",                                       ex1: "Perhaps she forgot.",                        ex2: "Perhaps you could help?",              id_translation: "mungkin / barangkali",                idDef: "Digunakan untuk menyatakan ketidakpastian.",                          idEx1: "Mungkin dia lupa."),
        Word(rank: 731, word: "throughout",   pos: "preposition", ipa: "/θruːˈaʊt/",    def: "In every part of a place or object.",                                              alt: "During the whole of a period.",                                        ex1: "Snow fell throughout the night.",            ex2: "Famous throughout the world.",         id_translation: "di seluruh / sepanjang",              idDef: "Di setiap bagian suatu tempat.",                                      idEx1: "Salju turun sepanjang malam."),
        Word(rank: 760, word: "circumstance", pos: "noun",        ipa: "/ˈsɜːkəmstəns/", def: "A fact or condition connected with an event or action.",                           alt: "One's financial situation.",                                           ex1: "Under the circumstances, we waited.",        ex2: "Reduced circumstances.",               id_translation: "keadaan / situasi",                   idDef: "Fakta atau kondisi yang terhubung dengan peristiwa.",                 idEx1: "Dalam keadaan seperti itu, kami menunggu."),
        Word(rank: 794, word: "appreciate",   pos: "verb",        ipa: "/əˈpriːʃieɪt/",  def: "To recognise the full worth of; to be grateful for.",                              alt: "To rise in value over time.",                                          ex1: "I appreciate your help.",                    ex2: "The house appreciated in value.",      id_translation: "menghargai / bersyukur",              idDef: "Mengenali nilai sesuatu; bersyukur.",                                 idEx1: "Saya menghargai bantuanmu."),
        Word(rank: 823, word: "responsible",  pos: "adjective",   ipa: "/rɪˈspɒnsəbəl/", def: "Having an obligation to do something, or having control over someone.",            alt: "Being the cause of something.",                                        ex1: "She is responsible for the team.",           ex2: "Who is responsible for this?",         id_translation: "bertanggung jawab",                   idDef: "Memiliki kewajiban untuk melakukan sesuatu.",                         idEx1: "Dia bertanggung jawab atas tim."),
        Word(rank: 856, word: "demonstrate",  pos: "verb",        ipa: "/ˈdemənstreɪt/", def: "To clearly show the existence or truth of something by evidence.",                 alt: "To take part in a public protest.",                                    ex1: "The data demonstrate a trend.",              ex2: "Thousands demonstrated in the square.", id_translation: "mendemonstrasikan / membuktikan",    idDef: "Menunjukkan keberadaan sesuatu melalui bukti.",                       idEx1: "Data menunjukkan sebuah tren."),
        Word(rank: 889, word: "frequently",   pos: "adverb",      ipa: "/ˈfriːkwəntli/", def: "Regularly or habitually; often.",                                                  alt: "At short intervals.",                                                  ex1: "He frequently arrives late.",                ex2: "Frequently asked questions.",          id_translation: "sering / kerap",                      idDef: "Secara teratur atau terbiasa; sering.",                               idEx1: "Dia sering terlambat datang."),
        Word(rank: 921, word: "consequence",  pos: "noun",        ipa: "/ˈkɒnsɪkwəns/",  def: "A result or effect of an action or condition.",                                    alt: "Importance or relevance.",                                             ex1: "Face the consequences.",                     ex2: "A matter of little consequence.",      id_translation: "konsekuensi / akibat",                idDef: "Hasil atau efek dari suatu tindakan.",                                idEx1: "Hadapi konsekuensinya."),
        Word(rank: 954, word: "nevertheless", pos: "adverb",      ipa: "/ˌnevəðəˈles/",  def: "In spite of that; notwithstanding; all the same.",                                 alt: "However; even so.",                                                    ex1: "It was hard; nevertheless, we tried.",       ex2: "She was tired but went nevertheless.", id_translation: "meskipun demikian / namun",           idDef: "Meskipun demikian; walaupun begitu.",                                 idEx1: "Itu sulit; meskipun demikian, kami mencoba."),
        Word(rank: 988, word: "fundamental",  pos: "adjective",   ipa: "/ˌfʌndəˈmentəl/",def: "Forming a necessary base or core; of central importance.",                         alt: "Affecting the foundation; basic.",                                     ex1: "A fundamental principle.",                   ex2: "Fundamental human rights.",            id_translation: "fundamental / mendasar",              idDef: "Membentuk dasar yang diperlukan; sangat penting.",                    idEx1: "Sebuah prinsip yang mendasar."),
        Word(rank: 1024,word: "acknowledge",  pos: "verb",        ipa: "/əkˈnɒlɪdʒ/",   def: "To accept or admit the existence or truth of something.",                          alt: "To show that one has noticed someone.",                                ex1: "He acknowledged his mistake.",               ex2: "She acknowledged me with a nod.",      id_translation: "mengakui / menyadari",                idDef: "Menerima atau mengakui kebenaran sesuatu.",                           idEx1: "Dia mengakui kesalahannya."),
        Word(rank: 1057,word: "contemporary", pos: "adjective",   ipa: "/kənˈtemprəri/", def: "Living or occurring at the same time; modern.",                                    alt: "Belonging to the present time.",                                       ex1: "Contemporary art.",                          ex2: "A contemporary of Newton.",            id_translation: "kontemporer / modern",                idDef: "Hidup atau terjadi pada waktu yang sama; modern.",                    idEx1: "Seni kontemporer."),
        Word(rank: 1092,word: "distinguish",  pos: "verb",        ipa: "/dɪˈstɪŋɡwɪʃ/", def: "To recognise or treat someone or something as different.",                         alt: "To make oneself noteworthy.",                                          ex1: "Distinguish right from wrong.",              ex2: "She distinguished herself in science.", id_translation: "membedakan / memilah",               idDef: "Mengenali sesuatu sebagai berbeda.",                                  idEx1: "Bedakan yang benar dari yang salah."),
        Word(rank: 1128,word: "appropriate",  pos: "adjective",   ipa: "/əˈprəʊpriət/",  def: "Suitable or proper in the circumstances.",                                         alt: "To take for one's own use.",                                           ex1: "Wear appropriate clothing.",                 ex2: "An appropriate response.",             id_translation: "sesuai / tepat / pantas",             idDef: "Cocok atau benar dalam situasi tersebut.",                            idEx1: "Kenakan pakaian yang sesuai."),
        Word(rank: 1163,word: "phenomenon",   pos: "noun",        ipa: "/fɪˈnɒmɪnən/",  def: "A fact or situation that is observed to exist or happen.",                         alt: "A remarkable person or thing.",                                        ex1: "A natural phenomenon.",                      ex2: "She is a phenomenon on stage.",        id_translation: "fenomena / gejala",                   idDef: "Fakta atau situasi yang diamati terjadi.",                            idEx1: "Fenomena alam."),
        Word(rank: 1201,word: "inevitable",   pos: "adjective",   ipa: "/ɪnˈevɪtəbəl/", def: "Certain to happen; unavoidable.",                                                  alt: "So frequent as to be expected.",                                       ex1: "Change is inevitable.",                      ex2: "The inevitable traffic jam.",          id_translation: "tak terhindarkan / pasti terjadi",    idDef: "Pasti akan terjadi; tidak bisa dihindari.",                           idEx1: "Perubahan tidak bisa dihindari."),
        Word(rank: 1244,word: "substantial",  pos: "adjective",   ipa: "/səbˈstænʃəl/",  def: "Of considerable importance, size, or worth.",                                      alt: "Strongly built or made.",                                              ex1: "A substantial sum of money.",                ex2: "A substantial meal.",                  id_translation: "substansial / besar",                 idDef: "Memiliki kepentingan atau ukuran yang cukup besar.",                  idEx1: "Jumlah uang yang besar."),
        Word(rank: 1288,word: "perspective",  pos: "noun",        ipa: "/pəˈspektɪv/",   def: "A particular attitude toward or way of regarding something.",                      alt: "The art of giving depth on a flat surface.",                           ex1: "From my perspective, it works.",             ex2: "Drawing in perspective.",              id_translation: "perspektif / sudut pandang",          idDef: "Cara atau sudut pandang dalam memandang sesuatu.",                    idEx1: "Dari sudut pandang saya, itu berhasil."),
        Word(rank: 1333,word: "emphasise",    pos: "verb",        ipa: "/ˈemfəsaɪz/",    def: "To give special importance or prominence to something.",                           alt: "To stress a word or phrase.",                                          ex1: "She emphasised the deadline.",               ex2: "He emphasised every syllable.",        id_translation: "menekankan / menggarisbawahi",        idDef: "Memberikan kepentingan khusus pada sesuatu.",                         idEx1: "Dia menekankan batas waktu itu."),
        Word(rank: 1389,word: "hypothesis",   pos: "noun",        ipa: "/haɪˈpɒθəsɪs/",  def: "A proposed explanation made on limited evidence as a starting point.",             alt: "A supposition put forward for testing.",                               ex1: "Test the hypothesis.",                       ex2: "A working hypothesis.",                id_translation: "hipotesis / dugaan ilmiah",           idDef: "Penjelasan yang diusulkan sebagai titik awal.",                       idEx1: "Uji hipotesis tersebut."),
        Word(rank: 1442,word: "deliberate",   pos: "adjective",   ipa: "/dɪˈlɪbərət/",   def: "Done consciously and intentionally.",                                              alt: "Careful and unhurried.",                                               ex1: "A deliberate insult.",                       ex2: "Slow, deliberate movements.",          id_translation: "disengaja / terencana",               idDef: "Dilakukan secara sadar dan sengaja.",                                 idEx1: "Penghinaan yang disengaja."),
        Word(rank: 1503,word: "comprehensive",pos: "adjective",   ipa: "/ˌkɒmprɪˈhensɪv/",def: "Complete; including all or nearly all elements or aspects.",                     alt: "Of large content or scope.",                                           ex1: "A comprehensive guide.",                     ex2: "Comprehensive insurance.",             id_translation: "komprehensif / menyeluruh",           idDef: "Lengkap; mencakup semua elemen atau aspek.",                          idEx1: "Panduan yang komprehensif."),
        Word(rank: 1567,word: "correspond",   pos: "verb",        ipa: "/ˌkɒrɪˈspɒnd/",  def: "To have a close similarity; to match or agree almost exactly.",                   alt: "To communicate by exchanging letters.",                                ex1: "The accounts correspond.",                   ex2: "They corresponded for years.",         id_translation: "bersesuaian / cocok",                 idDef: "Memiliki kesamaan yang erat; hampir sama persis.",                    idEx1: "Catatannya bersesuaian."),
        Word(rank: 1634,word: "anticipate",   pos: "verb",        ipa: "/ænˈtɪsɪpeɪt/",  def: "To expect or predict; to act in advance of a future event.",                      alt: "To look forward to.",                                                  ex1: "We anticipate delays.",                      ex2: "She anticipated his question.",        id_translation: "mengantisipasi / memperkirakan",      idDef: "Mengharapkan atau bertindak sebelum peristiwa mendatang.",            idEx1: "Kami mengantisipasi keterlambatan."),
        Word(rank: 1702,word: "simultaneous", pos: "adjective",   ipa: "/ˌsɪməlˈteɪniəs/",def: "Occurring, operating, or done at the same time.",                                 alt: "Existing or happening together.",                                      ex1: "Simultaneous translation.",                  ex2: "Two simultaneous events.",             id_translation: "simultan / bersamaan",                idDef: "Terjadi atau dilakukan pada waktu yang sama.",                        idEx1: "Penerjemahan simultan."),
    ]
}
